markdown            : GFM
# theme               : minimau
rl: "https://pod.hubbe.net" # the base hostname & protocol for your site

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-seo-tag
  - jekyll-titles-from-headings

whitelist:
  - jekyll-redirect-from

minima:
  skin: dark
